name: CI
on:
  - pull_request
  - push
  - cron:  '0 0 * * 1'

jobs:
  minikube:
    runs-on: ubuntu-latest
    steps:

      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup Minikube
        uses: manusa/actions-setup-minikube@v2.3.0
        with:
          minikube version: 'v1.16.0'
          kubernetes version: 'v1.19.2'
          github token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install socat
        run: |
          sudo apt update
          sudo apt install socat

      - name: Create a new namespace
        run: kubectl create ns bookstack

      - name: Create database-credentials-secret
        run: |
          kubectl create secret generic bookstack-database \
            --from-literal password=$(cat /dev/urandom | env LC_CTYPE=C tr -dc a-zA-Z0-9 | head -c 32; echo) \
            --from-literal root=$(cat /dev/urandom | env LC_CTYPE=C tr -dc a-zA-Z0-9 | head -c 32; echo) \
            --from-literal username=bookstack-user \
            -n bookstack

      - name: Deploy mariadb
        run: kubectl apply -f mariadb.yaml -n bookstack

      - name: Wait a bit
        run: sleep 20s

      - name: Deploy BookStack
        run: kubectl apply -f bookstack.yaml -n bookstack

      - name: Wait a bit
        run: kubectl wait --for=condition=available deployment/bookstack -n bookstack --timeout=180s

      - name: port-forward bookstack
        run: |
          kubectl port-forward service/bookstack -n bookstack 8080:80 &
          sleep 5s

      - name: log mariadb
        run: kubectl logs deployment/mariadb -n bookstack

      - name: log bookstack
        run: kubectl logs deployment/bookstack -n bookstack

      - name: make sure bookstack is running
        run: curl http://localhost:8080 --fail
