name: CI
on:
  - pull_request
  - push

jobs:
  minikube:
    runs-on: ubuntu-latest
    steps:

      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup Minikube
        uses: manusa/actions-setup-minikube@v2.0.1
        with:
          minikube version: 'v1.13.1'
          kubernetes version: 'v1.19.2'
          github token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create a new namespace
        run: kubectl create ns bookstack

      - name: Create database-credentials-secret
        run: |
          kubectl create secret generic bookstack-database \
            --from-literal password=$(cat /dev/urandom | env LC_CTYPE=C tr -dc a-zA-Z0-9 | head -c 32; echo) \
            --from-literal root=$(cat /dev/urandom | env LC_CTYPE=C tr -dc a-zA-Z0-9 | head -c 32; echo) \
            --from-literal username=bookstack-user \
            -n bookstack

      - name: Deploy mariadb
        run: kubectl apply -f mariadb.yaml -n bookstack

      - name: Wait a bit
        run: sleep 20s

      - name: Deploy BookStack
        run: kubectl apply -f bookstack.yaml -n bookstack

      - name: Wait a bit
        run: sleep 20s

      - name: port forward bokstack
        run: kubectl port-forward -n bookstack $(kubectl get pods -n bookstack --no-headers | grep bookstack | tr -s ' ' | cut -d ' ' -f 1) 8080:80 &

      - name: Wait a bit
        run: sleep 5s

      - name: make sure bookstack is running
        run: curl http://localhost:8080 --fail
